In [112]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [113]:
# Load Dataset
df = pd.read_csv(r"C:\Users\Awadhesh Kumaar\Downloads\Churn_Modelling.csv")

In [114]:
# show the first 5 data
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [115]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [116]:
# Remove the unnecesary columns 
df = df.drop(["RowNumber","CustomerId","Surname"],axis =1)

In [117]:
# Encode Categorical Variable
le_gender = LabelEncoder() # converting text data into numbers
df["Gender"] = le_gender.fit_transform(df["Gender"])
df = pd.get_dummies(df,columns=["Geography"],drop_first=True)# One hot encoding

In [118]:
# Features and Target
x = df.drop("Exited",axis = 1)# Removing only exited data from the table
# if here mention axis = 0 they remove the rows data
y = df["Exited"]

In [119]:
print(x)

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...              False            False
1             608       0  ...              False             True
2             502       0  ...              False            False
3             699       0  ...              False            False
4             850       0  ...              False             True
...           ...     ...  ...                ...              ...
9995          771       1  ...              False            False
9996          516       1  ...              False            False
9997          709       0  ...              False            False
9998          772       1  ...               True            False
9999          792       0  ...              False            False

[10000 rows x 11 columns]

In [120]:
print(y)

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [121]:
# Train - Test - Split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [122]:
# Feature Scalling
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [123]:
# Build ANN Model
model = Sequential()

model.add(Dense(16,activation='relu',input_dim = x_train.shape[1]))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

c:\Users\Awadhesh Kumaar\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [124]:
# Compile model
model.compile(
    optimizer = 'adam', 
    loss = 'binary_crossentropy',
    metrics = ['accuracy']
)

In [125]:
# train model
history = model.fit(
    x_train, y_train, epochs = 50, batch_size = 32, validation_split=0.2)

Epoch 1/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7802 - loss: 0.5641 - val_accuracy: 0.7994 - val_loss: 0.4915
Epoch 2/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8062 - loss: 0.4612 - val_accuracy: 0.8294 - val_loss: 0.4226
Epoch 3/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8152 - loss: 0.4299 - val_accuracy: 0.8325 - val_loss: 0.4101
Epoch 4/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8219 - loss: 0.4190 - val_accuracy: 0.8338 - val_loss: 0.4043
Epoch 5/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8280 - loss: 0.4108 - val_accuracy: 0.8338 - val_loss: 0.3989
Epoch 6/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8320 - loss: 0.4013 - val_accuracy: 0.8431 - val_loss: 0.3917
Epoch 7/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8402 - loss: 0.3884 - val_accuracy: 0.8519 - val_loss: 0.3810
Epoch 8/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8439 - loss: 0.3730 - val_accuracy: 0.8512 - val_loss: 0.3692
Epoch 9/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8491 - loss: 0.3607 - val_accuracy: 0.8575 - val_loss: 0.3603
Epoch 10/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8550 - loss: 0.3530 - val_accuracy: 0.8519 - val_loss: 0.3569
Epoch 11/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8583 - loss: 0.3485 - val_accuracy: 0.8562 - val_loss: 0.3548
Epoch 12/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8572 - loss: 0.3459 - val_accuracy: 0.8594 - val_loss: 0.3529
Epoch 13/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8570 - loss: 0.3443 - val_accuracy: 0.8581 - val_loss: 0.3514
Epoch 14/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3426 - val_accuracy: 0.8606 - val_loss: 0.3519
Epoch 15/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8600 - loss: 0.3411 - val_accuracy: 0.8587 - val_loss: 0.3504
Epoch 16/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3402 - val_accuracy: 0.8569 - val_loss: 0.3493
Epoch 17/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8605 - loss: 0.3396 - val_accuracy: 0.8569 - val_loss: 0.3492
Epoch 18/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.3387 - val_accuracy: 0.8556 - val_loss: 0.3482
Epoch 19/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3375 - val_accuracy: 0.8575 - val_loss: 0.3489
Epoch 20/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8591 - loss: 0.3374 - val_accuracy: 0.8569 - val_loss: 0.3472
Epoch 21/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8600 - loss: 0.3367 - val_accuracy: 0.8575 - val_loss: 0.3482
Epoch 22/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3359 - val_accuracy: 0.8562 - val_loss: 0.3466
Epoch 23/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8605 - loss: 0.3353 - val_accuracy: 0.8569 - val_loss: 0.3473
Epoch 24/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8616 - loss: 0.3349 - val_accuracy: 0.8594 - val_loss: 0.3494
Epoch 25/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3346 - val_accuracy: 0.8594 - val_loss: 0.3468
Epoch 26/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3337 - val_accuracy: 0.8594 - val_loss: 0.3478
Epoch 27/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8611 - loss: 0.3339 - val_accuracy: 0.8575 - val_loss: 0.3463
Epoch 28/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8616 - loss: 0.3334 - val_accuracy: 0.8587 - val_loss: 0.3467
Epoch 29/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.3332 - val_accuracy: 0.8581 - val_loss: 0.3468
Epoch 30/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3323 - val_accuracy: 0.8612 - val_loss: 0.3476
Epoch 31/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8623 - loss: 0.3319 - val_accuracy: 0.8569 - val_loss: 0.3453
Epoch 32/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3322 - val_accuracy: 0.8569 - val_loss: 0.3442
Epoch 33/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8637 - loss: 0.3319 - val_accuracy: 0.8600 - val_loss: 0.3462
Epoch 34/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3317 - val_accuracy: 0.8525 - val_loss: 0.3439
Epoch 35/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8622 - loss: 0.3312 - val_accuracy: 0.8556 - val_loss: 0.3450
Epoch 36/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3306 - val_accuracy: 0.8550 - val_loss: 0.3437
Epoch 37/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3304 - val_accuracy: 0.8550 - val_loss: 0.3440
Epoch 38/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3302 - val_accuracy: 0.8569 - val_loss: 0.3431
Epoch 39/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3297 - val_accuracy: 0.8569 - val_loss: 0.3432
Epoch 40/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8623 - loss: 0.3294 - val_accuracy: 0.8519 - val_loss: 0.3430
Epoch 41/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8641 - loss: 0.3292 - val_accuracy: 0.8537 - val_loss: 0.3442
Epoch 42/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8642 - loss: 0.3286 - val_accuracy: 0.8537 - val_loss: 0.3439
Epoch 43/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3288 - val_accuracy: 0.8544 - val_loss: 0.3440
Epoch 44/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8628 - loss: 0.3284 - val_accuracy: 0.8562 - val_loss: 0.3452
Epoch 45/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3285 - val_accuracy: 0.8569 - val_loss: 0.3425
Epoch 46/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3283 - val_accuracy: 0.8500 - val_loss: 0.3443
Epoch 47/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3280 - val_accuracy: 0.8556 - val_loss: 0.3437
Epoch 48/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3276 - val_accuracy: 0.8544 - val_loss: 0.3442
Epoch 49/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3272 - val_accuracy: 0.8556 - val_loss: 0.3432
Epoch 50/50
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8650 - loss: 0.3269 - val_accuracy: 0.8587 - val_loss: 0.3424

In [126]:
# User Input

creditscore = int(input("Enter Credit Score(350 - 850): "))
gender = input("Gender (Male/Female): ").capitalize()
age = int(input("Enter Age(18 - 92): "))
tenure = int(input("Enter Tenure(0-10): "))
balance = float(input("Enter Balance(0-250898): "))
numofproducts = int(input("Enter Number of Products(1-4): "))
hascrcard = int(input("Has Credit Card (1/0): "))
isactivemember = int(input("Is Active Member (1/0): "))
estimatedsalary = float(input("Enter Estimated Salary(11-199992): "))
geography = input("Geography (France/Germany/Spain): ").capitalize()

In [127]:
# Gender Encoding

if gender == "Male":
    gender = 1
else:
    gender = 0

# Geography Encoding

geography_germany = 0
geography_spain = 0

if geography == "Germany":
    geography_germany = 1
elif geography == "Spain":
    geography_spain = 1

In [128]:
df.describe()

        CreditScore        Gender  ...  EstimatedSalary        Exited
count  10000.000000  10000.000000  ...     10000.000000  10000.000000
mean     650.528800      0.545700  ...    100090.239881      0.203700
std       96.653299      0.497932  ...     57510.492818      0.402769
min      350.000000      0.000000  ...        11.580000      0.000000
25%      584.000000      0.000000  ...     51002.110000      0.000000
50%      652.000000      1.000000  ...    100193.915000      0.000000
75%      718.000000      1.000000  ...    149388.247500      0.000000
max      850.000000      1.000000  ...    199992.480000      1.000000

[8 rows x 10 columns]

In [129]:
# user data
user_data = [[
    creditscore,
    gender,
    age,
    tenure,
    balance,
    numofproducts,
    hascrcard,
    isactivemember,
    estimatedsalary,
    geography_germany,
    geography_spain
]]

In [130]:
# Scale data
user_data = scaler.transform(user_data)

c:\Users\Awadhesh Kumaar\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [131]:
# Evaluate Model
loss, accuracy = model.evaluate(x_test, y_test)
print("Accuracy:",accuracy)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8555 - loss: 0.3426
Accuracy: 0.8554999828338623

In [132]:
# Predictions

Predictions = model.predict(user_data)
Predictions = (Predictions > 0.5)
print(Predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
[[False]]

In [133]:
# Final Result
print("You have creditscore:",creditscore)
print("You have entered gender:",gender)
print("You have entered age :",age)
print("You have entered tenure:",tenure)
print("You have entered balance:",balance)
print("You have entered numofproduct:",numofproducts)
print("You have entered isactivemember:",isactivemember)
print("YOu have entered estimatedsalary:",estimatedsalary)
print("You have entered geography_germany:",geography_germany)
print("You have entered geography_spain:",geography_spain)
if Predictions[0][0] > 0.5:
    print("Customer Will Leave (Churn)")
else:
    print("Customer Will Stay")

You have creditscore: 350
You have entered gender: 1
You have entered age : 18
You have entered tenure: 0
You have entered balance: 0.0
You have entered numofproduct: 1
You have entered isactivemember: 1
YOu have entered estimatedsalary: 11.0
You have entered geography_germany: 0
You have entered geography_spain: 0
Customer Will Stay

In [134]:
# Confusion matrix
from sklearn.metrics import confusion_matrix, classification_report
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test,y_pred))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[1529   78]
 [ 211  182]]
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1607
           1       0.70      0.46      0.56       393

    accuracy                           0.86      2000
   macro avg       0.79      0.71      0.74      2000
weighted avg       0.84      0.86      0.84      2000